FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# C++ dev tools & libs
RUN apt-get update && \
    apt-get install -y build-essential gcc mingw-w64 gdb gdbserver ninja-build cmake \
        libasio-dev libssl-dev && \
    apt-get clean

WORKDIR /app
VOLUME /app/build

CMD ["bash"]